Make sprint 6 implementation
StanislavFishkov/java-kanban pull request #1
Opened 2024-04-14 22:00 UTC by StanislavFishkov

###  Изменение логики хранения истории просмотра задач в классе InMemoryHistoryManager:
* Хранится только последний просмотр;
* Убрано ограничение на 10 элементов в истории просмотра;
* История хранится по порядку просмотра (при обращении через getHistory());
* Обновлены тесты.

### Прочие изменения:
* При удалении задачи в классе InMemoryTaskManager удаляется история просмотров этой задачи (в случае эпика и история просмотра его сабтасков);
* Изменен код main для более наглядного просмотра новой логики истории.

2024-04-15 17:46 UTC, z8q requested changes

2024-04-15 17:46 UTC, z8q commented on src/kanban/service/InMemoryTaskManager.java
> +        historyManager.remove(id);
На методах deleteAllTasks, deleteAllSubtasks, deleteAllEpics нужно тоже производить удаление из истории

2024-04-16 00:18 UTC, StanislavFishkov commented on src/kanban/service/InMemoryTaskManager.java
> +        historyManager.remove(id);
Кирилл, привет!

Точно, спасибо! Забыл про эти методы. Исправил, сделал новый коммит.

2024-04-16 18:02 UTC, z8q approved these changes

2024-04-18 19:40 UTC, merged