Make Sprint 7 implementation
StanislavFishkov/java-kanban pull request #2
Opened 2024-05-04 19:20 UTC by StanislavFishkov

###  Добавлен новый класс FileBackedTaskManager реализующий интерфейс TaskManager и сохраняющий свое состояние в файл при любом изменении, с возможностью восстановить состояние из файла соответствующей структуры:
* В классе также реализован метод main для тестирования пользовательского сценария, предложенного в качестве дополнительно задания.
* Добавлен тестовый класс FileBackedTaskManagerTest.

### Прочие изменения:
* Добавлены перечисление TaskTypes и метод getTaskType() у классов Task, Epic  и Subtask, возвращающий соответствующее значение;
* У класса InMemoryTaskManager поля, хранящие мапы задач, эпиков и сабтасков сделаны protected. Необходимо для восстановления менеджера-наследника FileBackedTaskManager из файла;
* У класс Epic добавлен конструктор, позволяющий указать status. Необходимо для восстановления эпиков из файла;
* В утилитарном классе Managers теперь по умолчанию возвращается объект класса FileBackedTaskManager, инициализированный файлом "resources/task.csv" для сохранения состояния;
* Содержимое папки "resources/" помечено как untracked.

2024-05-05 18:06 UTC, z8q requested changes

2024-05-05 18:06 UTC, z8q commented on src/kanban/service/FileBackedTaskManager.java
> +    static String toString(Task task) {
На toString и fromString можно поставить модификаторы доступа public.
Их можно вынести в отдельный класс, например TaskParser или TaskMapper, методы при этом можно оставить статическими, чтобы вызов был такого вида:
TaskParser.toString(someTask) -  без создания new TaskParser

При этом метод toString лучше переименовать, так как toString - это один из методов класса Object, который мы переопределяем в некоторых классах.  Просто чтобы не возникала путаница

2024-05-05 20:20 UTC, StanislavFishkov commented on src/kanban/service/FileBackedTaskManager.java
> +    static class ManagerSaveException extends RuntimeException {
Понял, готово.

2024-05-05 20:23 UTC, StanislavFishkov commented on src/kanban/service/FileBackedTaskManager.java
> +            switch (task1.getTaskType()) {
Да, конечно, у меня именно так реализовано в InMemoryHistoryManager копирование задач, но тут явно посоветовали перечисление создать: "Создайте enum с типами задач.". Я решил, что будет удобнее для универсальности, если каждая задача сама будет "сообщать" свой тип, когда это требуется.

2024-05-05 20:23 UTC, StanislavFishkov commented on src/kanban/service/FileBackedTaskManager.java
> +    static String toString(Task task) {
Да, так красивее, согласен. Готово.

2024-05-06 18:06 UTC, z8q approved these changes

2024-05-10 00:58 UTC, merged