Make Sprint 8 implementation
StanislavFishkov/java-kanban pull request #3
Opened 2024-05-13 00:36 UTC by StanislavFishkov

2024-05-13 19:10 UTC, z8q requested changes

2024-05-13 19:10 UTC, z8q commented on src/kanban/service/InMemoryTaskManager.java
>      public ArrayList<Subtask> getEpicSubtasks(Epic epic) {
Можно сделать проверки входящих аргументов, чтобы избежать NullPointerException.

2024-05-13 19:10 UTC, z8q commented on src/kanban/model/Epic.java
>          this.subtasks = subtasks;
Можно потестировать, как программа будет реагировать на такое взаимодействие

```JAVA
        Epic epic = taskManager.getEpic(epicId);
        epic.setSubtasks(null);
        taskManager.updateEpic(epic);
```

2024-05-17 00:45 UTC, StanislavFishkov commented on src/kanban/model/Epic.java
>          this.subtasks = subtasks;
Теперь, кажется, нормально)

2024-05-17 00:45 UTC, StanislavFishkov commented on src/kanban/service/InMemoryTaskManager.java
>      public void deleteTask(Integer id) {
Готово.

2024-05-17 00:46 UTC, StanislavFishkov commented on src/kanban/service/InMemoryTaskManager.java
>      public ArrayList<Subtask> getEpicSubtasks(Epic epic) {
Готово.

2024-05-17 18:56 UTC, z8q approved these changes

2024-05-25 13:31 UTC, merged